#!/usr/bin/env python3
print("CONVERSOR DE GRADOS FAHRENHEIT A GRADOS CELSIUS")
F=int(input("Grados fahrenheit: "))
#INT PERMITE RECOGER EL VALOR INTEGER QUE VAMOS A INTRODUCIR
#POR LO TANTO F SERÁ IGUAL A LOS GRADOS FAHRENHEIT QUE SE INTRODUZCAN
print("Grados Celsius:{}".format((F-32)*5/9))
#.FORMAT LO QUE HARÁ ES DEVOLVER EL RESULTADO DE LA OPERACIÓN DENTRO DE {}